name: analyse

on:
  workflow_call:
    inputs:
      languages:
        description: "Optional input"
        required: false
        type: string
        default: "['javascript', 'csharp']"
jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJson(inputs.languages)}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{matrix.language}}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

